### ISSUE TITLE
Adopt a new Web Development Stack for use with Moja Global

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/About_moja_global#121]
## Motivation 

[Moja Global](http://moja.global/) is the premier platform that showcases the work and the impact of Moja Global in the long run. It also consists of all the information that a user might need to know about the same, without delving into the Code, including the News and Webinars that are being run. 

However a quick test, it is realized that the Moja Global Website is powered by WordPress, which uses a traditional PHP-based CMS to power the Frontend, which is enhanced by the use of Javascript and JQuery. With respect to responsiveness and SEO, there are plenty of disadvantages here: 

- According to this report by PageSpeed Insights [here](https://developers.google.com/speed/pagespeed/insights/?url=https://moja.global/), the Website ranks 54 on Mobile Devices and 76 on Desktop Devices. 
- Usage of a CMS limits the scope of Development by a huge margin. The Code isn't hosted anywhere and requires intensive maintenance for quick walk-throughs. 
- UI/UX of the Website is quite limited in scope and can be enhanced further for a more immersive experience. 

## Requirements 

Here are some of the requirements that we can expect out of a new website:
- Implementation of Unit-Testing can be made possible over the User Interface allowing the code available for a wider contribution through Open-Source Contribution.
- Usage of a modern Javascript Technology Stack can be used to benefit from a wider community of UI Components that we can plugin and make use of. 
- Being heavily optimized for Performance, they have wider flexibility in development and maintenance. 

## Proposal 

Since building and maintaining a complete Website is an essential task, I have thought of a generalized application that can be used to ease the workflow of getting a website up and running. For this purpose, I have fixated upon <b>GatsbyJS</b> for the purpose of building the Website, if needed anew.

We can migrate the whole website to GatsbyJS along with all the data into an easily maintainable data source. The new website would be a highly refined version of the current site in terms of the look and feel and the maintainability.

Using Gatsby JS would be a good choice because it is lightweight, is optimized for these kinds of applications, has good documentation and is built on top of ReactJS. We can also use a UI Kit as it will help make the development time much faster as we can focus more on business logic rather than on styling commonly used components. Some good examples can be:
- [React Material UI](https://material-ui.com/)  
- [Ant Design](https://ant.design/)
- [React Bootstrap](https://react-bootstrap.github.io/)

Apart from that, we can use Markdown or a JSON/YAML file as our primary data source. This would make it easy for us to add information, even if a Contributor has not much idea about Web Development.

## Alternatives considered 

Some of the further alternatives are using Vue and Angular for the purpose. Angular is a fully-fledged Web Frontend Framework which has pretty good features for the user interface development. But when considering the performance and further development of the application, Vue can be a better choice for this application. 

Vue is a front-end framework which helps to build fast, progressive JavaScript applications quickly. Vue can potentially reduce the time of development compared to developing the application with Angular and Vue also helps in producing performant applications.

## Further Context 

The Issue has been posted in form of a rough proposal after a private discussion with @aornugent 

I would like to know further opinions about the same from @shubhamkarande13 @waridrox @abhi211199 @Tlazypanda 

Thanks ✌️

**Comment by waridrox** [comment]
I actually thought about this from the first time I visited the website but I did not know for certain if it was possible to actually change the website from our end. I thought maybe the main authorities might prevent that from happening 😅. 

The points highlighted by @HarshCasper are very crucial especially if we consider the report from the [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https://moja.global/) and the [BuiltWith](https://builtwith.com/?https%3a%2f%2fmoja.global%2f) tool.

Sure, the current website gets the job done, but if we consider the enhancements that can be made in terms of fast loading time, better SEO optimization, and usability, I think it’s worth considering what the modern tech stack brings to the table. 

I cannot comment on the framework of choice because I do not have much expertise in that regard but would totally support the revamp idea and would like to contribute to it wherever possible if the proposal gets implemented 😊.

**Comment by aornugent** [comment]
Thanks @HarshCasper. In an open community like moja global, any topic should be open for discussion and it is important that we develop community buy-in before expending any effort coding. Well done for sharing your ideas up front.

I would like to use this issue is to seek requests for comment on the adoption of a common Javascript UI framework for moja global projects. We may find that separate issues are required for design documentation of specific elements like the moja.global homepage. 

As I see it, the benefits of select one JS framework are:
- a shared modern user experience across all projects
- automated component testing to reduce UI bugs
- reusability of components across projects to reduce development time
- capability building within the community

Wikimedia provide a good evaluation of the benefits and requirements of adopting a JS framework: https://phabricator.wikimedia.org/T241180

For the specific application of static websites like the moja.global homepage, there are additional benefits like improved performance, automated build tools, reduced hosting costs and shared community maintenance (i.e. open to pull requests). 

However, WordPress provides additional administration tools, a CMS frontend and simplified hosting environment that are useful to the current maintainers. The proposed contributors website in #110 might be a better candidate to evaluate a new web stack.

I'd like to hear from anyone that has an opinion, especially @abhi211199 on his experience with using React for the JSON inteface and @shubhamkarande13 on his plan to develop a web based UI for FLINT. We should identify the broad requirements for all moja global projects and evaluate our options before making a decision. The discussion should inform @waridrox with his proposal to develop a UX strategy [#4](https://github.com/moja-global/Google_Summer_of_Code/issues/5)

**Comment by waridrox** [comment]
As pointed out, we have to also look from the perspective of the maintainers, they cannot go and implement new changes in the website every now and then or rely on someone to do it when they have to release something important very quickly. For that reason, I think it is better to leave the official website in the hands of the maintainers and implement the idea in #110 😇

**Comment by abhi211199** [comment]
As far as the tech stack is concerned, Gatsby is a great choice for SSGs with diverse support of ReactJS, onboarding new content and tweaking the UI is super easy! But, in the context of refactoring the moja global website, I totally agree with @aornugent that Wordpress may be continued in the future to maintain the website, for maintaining/devising new projects, we can use JS frameworks!

Now, talking about my experience of building the JSON editor, I compared React and Angular and made an in-depth analysis during my proposal making phase and chalked out some points like:
- React has a very sleek file-structure while Angular generates a lot of files for maintaining components. So Angular increases load on the application and effects performance.
- Sending data to components and rendering them is very easy in the case of ReactJS.
- ReactJS provides great [Material UI](https://material-ui.com/) support.(This UI library is specific to ReactJS but we also have a dedicated [Material](https://material.angular.io/) design library for Angular)
- ReactJS works great with Electron apps.(Slack uses React in its websites and desktop app)
After analyzing these aspects, me and @mfellows decided to go forward with ReactJS!

But that being said, I have a very minimal experience with VueJS, and didn't consider it while analysing the frameworks!

As moja global is onboarding a lot of new contributors and new project ideas, I think it will be better if we choose a single uniform tech stack that can be used by existing and future contributors to maintain the projects, and in this case, my choice will always be React, as it will help us to quickly use any of the static site generators like Gatsby or NextJS, not only for projects, but will help us to make contribution portals or documentation sites with great ease!

**Comment by aornugent** [comment]
I asked a friend to review this topic, these are his notes:

> - The React vs Vue is an age old debate. I find React better for things that are likely to scale up a lot, whereas Vue is good for getting things going quickly. Vue has a lower barrier to entry and does scale well, React is harder but not as hard when using supporting frameworks
> -  If you want a static rendered React framework I'd go with Next.js rather than Gatsby as it's newer, more modern, more used (I think) and easier to use (in my experience). Next.js has nice runtime error notifications for development and dramatically reduces the barrier to entry of React
>  - The wordpress CMS issue is right at the heart of where our company is fighting right now. It's often easier for a non-technical user to manage data/content from one place (like a Wordpress admin area) than across multiple places, but that holds back tech progression. Those arguments for staying on Wordpress are valid, but you can totally use something like Contentful (which has a generous free tier) to manage your content, it integrates automatically with Netlify (hosting platform) and would allow you to build a frontend with Next.js/Vue/React/Gatsby/whatever and host it all basically for free with automatic content editor integrations like you do with Wordpress style CMSs.

Would someone be interested in evaluating something Contentful as a potential CMS frontend for our comms team? It might be useful for the Contributors site if we start publishing regular case studies on module development, FLINT architecture etc. @waridrox is also evaluating documentation generators for UI components such as https://storybook.js.org/ - it would be great to hear more.

Please propose other functional specifications relevant to choosing a web framework so that we can progress toward a decision.

**Comment by abhi211199** [comment]
SEO may be regarded as a very useful parameter, Googlebot and some other search engine crawlers tend to fetch the basic `index.html` boilerplate pages as the static site generators generally render content dynamically.

While Gatsby can handle [this easily](https://www.gatsbyjs.com/docs/how-to/adding-common-features/seo), I do not have a proper idea of how NextJS renders content/behave with web crawlers! 

Someone who is interested in analyzing the SSG choices may consider this point!

**Comment by waridrox** [comment]
Maybe this can be useful as far as the SEO is concerned...
[Screenshot_2021-01-27-19-23-53-873_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/58583793/106027093-91d4ec00-60f0-11eb-96c6-d86288b68b74.jpg)

**Comment by abhineet97** [comment]
From where I see it, [moja.global](https://moja.global) seems like a **content-only** website. People visit our website to learn about what we're doing, what are the latest updates, how can they get in touch with us, etc.

Now, why do we need a JavaScript framework for any of those purposes?

Don't get me wrong, I totally agree that the current website is slow, ugly and is hurting our visibility with its bad SEO — but I don't think that investing in a JS framework is required to solve this problem.

What, I think, we should focus on is, getting rid of costly and hard to improve WordPress (as originally suggested by @HarshCasper). Here's one way that, I think, we can achieve that (without worrying about React or Vue):

Use a JS framework-agnostic static site generator (like the award-winning [Eleventy](https://www.11ty.dev/)) to design a beautiful, standards conforming (and hence search engine friendly) website using bare HTML & CSS and then host it for free on [GitHub Pages](https://pages.github.com/).

If, after we've done that, there arises a need for adding some incredibly amount of interactivity, then and only then, I think, it'll be worthwhile to evaluate client-side JavaScript libraries.

**Comment by aornugent** [comment]
> Why do we need a JavaScript framework for any of those purposes?

Quick clarification: ideally we'd like to choose a JS framework that can be reused for all of our interfaces, including websites, apps (e.g. Electron), browser based interfaces for pre- and post-processing. This is so that UI components can be reused across our platform. 

The considerations about SSGs and content management should be secondary components that support the specific application of our UI/JS framework for websites. Does that make sense?
