### ISSUE TITLE
EPIC for Welcome bot

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#64]
Welcome bot is 
Specification is needed. 
Issue for adding config in import repo: <add link> @Tlazypanda 
Config file: Create PR for versionabout moja global (import repo)  @Tlazypanda <add link> 
@gmajan Should we add this to other repositories (FLINT,FLINT.example etc)??

Refer to  
1. how to setup the bots as admin https://docs.google.com/document/d/1B1k2kRpAdtl9U8v-ze-uO56m8rldIuiAG1nQoZRpyDI/edit?usp=drivesdk

**Comment by Tlazypanda** [comment]
@Patamap These issues have been resolved -

- Created and pr merged for config file in import-me https://github.com/moja-global/Import-Me/pull/6
- Decapitalized instances of moja global in about_moja_global https://github.com/moja-global/About_moja_global/pull/53

Now remaining is @gmajan  input on whether welcome bot config needs to be added to other repositories :v:

**Comment by gmajan** [comment]
Yes, welcome bot should be added to other repos except moja.canada and gcbm.animation 
Please communicate with the maintainers in advance so they can approve your PR.
Thank you

**Comment by Tlazypanda** [comment]
Hey @gmajan @Patamap I have added the pull requests for all repos except vcpkg(forked repo), Gsoc, Gsod (since these are discussion repos) and gcbm_animation (as mentioned by Guy). You can see the prs are linked in this issue so you can review and close here as well :sweat_smile: Thanks :v: 

Once we have merged these pull requests ,this issue can be moved to done :smile:

**Comment by Patamap** [comment]
@Tlazypanda, what is the sustainable solution for the future repo?

**Comment by Tlazypanda** [comment]
Update : since all repositories have rolled this out we can close this 😅
