### ISSUE TITLE
Greetbot on Slack for when newcomers join the slack

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#71]
Refer from https://github.com/moja-global/About_moja_global/issues/65. @Tlazypanda 
Updating here - greetbot setup on slack for

- Direct message when a newcomer joins.
- Channel message for when newcomers join #gsoc-general
To be updated/changed acc to the convenience of other slack members.
Can take this up in the next meeting

The result of the msg for greetbot
Hello @new_user_name !:wave: Welcome to moja global!:sparkling_heart:
Moja global fosters an open and welcoming environment for all our contributors.:cherry_blossom: Please adhere to our [Code Of Conduct](https://github.com/moja-global/About_moja_global/blob/master/CODE_OF_CONDUCT.md) and be respectful during all communications.
If you are new here and looking for channels to join, here are a few recommendations:
#gsoc-general - For all GSOC related announcements, queries and discussions
#newcomers - For all newly joined members of the community. Feel free to introduce yourself!
#random - A place for non-work related jibber-jabber
It is highly encouraged to have discussions in specific channels instead of in #general.
Moja global is delighted to have you here :) Hope you have a great time here 

@Tlazypanda, thanks for a new feature of Greetbot on Slack. for channels right now I have only set it up on gsoc-general as a demo.  Let me know where else to incorporate and what changes are to be done with the content? l
@gmajan,

**Comment by Patamap** [comment]
My proposal of the content below, 
-  Welcome to the development and science discussion channel for Moja Global. 

-  Feel free to ask questions about our projects (e.g. [FLINT](https://github.com/moja-global/FLINT) ) or reach out to the developers.6
-  Please remember to be kind and respectful in all discussions. These are our Code Of Conduct to keep in mind.
-  Change from @Random channel to be @general channel. A place for all opening and general topics that is not part of any topic.

**Comment by Tlazypanda** [comment]
Hey @Patamap I think that they are automatically added to general when they get added :sweat_smile:

**Comment by Tlazypanda** [comment]
@Patamap @gmajan Updating after meeting here:

### Greetbot updated to send this message on joining #general - 
@channel Hey everyone please give a warm welcome to @new_user_name! It's great to have you here :heart_decoration:
Feel free to introduce yourself or ask any questions or queries! Please be patient, we will try to get back to you as soon as possible! :raised_hands:
Welcome to moja global! :tada:

### Greetbot updated to send this direct message on joining moja global slack - 
Hello @new_user_name !:wave: Welcome to moja global!:sparkling_heart:
Moja global fosters an open and welcoming environment for all our contributors.:cherry_blossom: Please adhere to our [Code Of Conduct](https://github.com/moja-global/About_moja_global/blob/master/CODE_OF_CONDUCT.md) and be respectful during all communications.
If you are new here and looking for channels to join, here are a few recommendations:
#gsoc-general - For all GSOC related announcements,queries and discussions
#general  - For all work related discussions. If you are new feel free to introduce yourself!
It is highly encouraged to have discussions in specific channels instead of in #general.
Moja global is delighted to have you here :) Hope you have a great time here :sparkles:

If we are good with this we can close this :v:

**Comment by Tlazypanda** [comment]
@Patamap we can close this issue then :v: Can you please close this?
