### ISSUE TITLE
Choose Documentation platform

### ISSUE THREAD

**Issue by Patamap** [moja-global/About_moja_global#73]
**Summary**:  Establish a documentation platform for hosted documentation about Moja Global projects.

**Background:** Effective documentation is critical in technical projects – open source or otherwise. However, it's especially helpful for Moja Global because of the small team size and need to engage with the open-source community.

Better documentation for MojaGlobal means…
1. New contributors/contractors learn the pipeline/software quicker
2. Design decisions are better documented (less time back-tracking)
3. Enables other contributor-oriented documentation (e.g. issue / PR templates, see a xxx?)
4. Easier to tell a story (e.g. Opensource.com, see xxxx?)

**Details**
Choosing a platform should be based on what is most intuitive and easiest to maintain for the team. A popular platform is [ReadTheDocs](https://readthedocs.org/), which uses a Python-based toolchain. Thus, it also makes it an especially fantastic tool for Python projects, but it is still great for any programming language regardless. 
see the example: https://magicbox.readthedocs.io/en/latest/# 

Or [Just the doc](https://github.com/pmarsceill/just-the-docs) is good option. See the example: https://sabitarao.github.io/mojaglobal/

**Expected Outcome**
Better documentation means a better experience for people to contribute to our projects; enables us to bring new people into the community easier and also provide reference points for various design decisions in the future (i.e. why we did something the way we did)

**Comment by Tlazypanda** [comment]
I think hosting platform Read The Docs  should be used due to the following reasons:- 
Ranked highly among different hosting platforms.
Automatic updation on pushing commit
Easy to set up and troubleshooting support available easily due to the large community using it
Documentation is formatted using reStructuredText and the output is compiled by Sphinx.

**Comment by leitchy** [comment]
I agree, ReadTheDocs looks good.

**Comment by Patamap** [comment]
The chosen is done with **"ReadTheDocs"** 
The reason of selection are
- Ranked highly among different hosting platforms.
- Automatic updation on pushing commit
- Easy to set up and troubleshooting support available easily due to the large community using it
- Documentation is formatted using reStructuredText and the output is compiled by Sphinx.
- ReadTheDocs can be used for multiple programming language. 
- Independent research for JavaScript-style documentation toolchains proved that ReadTheDocs is the best tool for the job (see readthedocs/sphinx-autoapi#7).

**What's next**
- Research how we could bring programming documentation into the docs in an elegant way
-  Create the mockup in ReadTheDocs
- Discuss the structure and content of moja global github. 
[link to the map of current moja global GitHub repositories and the content within them](https://coggle.it/diagram/XvXuJhYkPIVpYBgV/t/available-content) thanks to @sabitara
- See the [first draft of the moja global doc structure.](https://sabitarao.github.io/mojaglobal/)  thanks to @sabitara

@sabitarao @Tlazypanda @gmajan

**Comment by Tlazypanda** [comment]
Adding here:
### Sumary of discussion:

 rST chosen over markdown to overcome the limitations of markdown giving importance to :- 
- pdf generation
- more uniformity and structure (markdown has many flavors)
- more features in terms of plugins

Also for jekyll vs readthedocs the primary premise was with readthedocs free version we will have a url of `name.readthedocs.io` but with jekyll we can have a subdomain to our website. So in conversation with the team, no issues found with the free version of readthedocs. 

Other points discussed that since Jekyll is ruby based local setup might be daunting to new contributors while readthedocs requires python installations comparitively easier (point made by @gmajan that we already have some python in our codebase so might be better to stick with it).

@Patamap point made in favor of readthedocs that since many huge organisations are already using it, it might be the safe option to go for.
